version: "3"
services:

  mysqldb:
    container_name: mysqldb
    image: mysql:8.3
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqldb
    networks:
      - demonetwork

  neo4j:
    image: neo4j:5.17.0
    ports:
      - "7690:7687"
    environment:
      NEO4J_AUTH: none
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
    networks:
      - demonetwork

networks:
  demonetwork:
    driver: bridge